<minecraft:stick>.addTooltip("Some modular machinery may have some structural deviations during construction, please solve it by yourself according to the projection");
<tconstruct:cast_custom:3>.addTooltip("banned");
<ic2:te:52>.addTooltip("banned");
<tconstruct:cast_custom:4>.addTooltip("banned");
<mekanism:basicblock3:13>.displayName="Creative Energy Cube(FULL)";
<mekanism:basicblock3:13>.addTooltip("200GFE(50GEU)");
<modularmachinery:youjiranliaofadianji_controller>.addTooltip("The direction of the furnace may be wrong when it is automatically built, so please modify it according to the projection");
<thermalfoundation:material:135>.addTooltip("cannot used for crafting");
<real_island_mod:jiyanfenshengji>.addTooltip("Increases the chance of sifting out infinity dust, but for some reason, only infinity dust can be sifted after using it");
<real_island_mod:jiyanfenshengji>.addTooltip("CANNOT use with luck upgrade");