mods.thermalexpansion.Refinery.removeRecipe(<liquid:coal>);
mods.thermalexpansion.Crucible.addRecipe(<liquid:crude_oil>*250,<real_island_mod:shiyou>, 2000);
mods.thermalexpansion.Transposer.addFillRecipe(<thermalfoundation:upgrade>, <real_island_mod:shengji_1>, <liquid:petrotheum>*500, 5000);
mods.thermalexpansion.Transposer.addFillRecipe(<thermalfoundation:upgrade:1>, <real_island_mod:shengji_2>, <liquid:aerotheum>*500, 5000);
mods.thermalexpansion.Transposer.addFillRecipe(<thermalfoundation:upgrade:2>, <real_island_mod:shengji_3>, <liquid:cryotheum>*500, 5000);
mods.thermalexpansion.Transposer.addFillRecipe(<thermalfoundation:upgrade:3>, <real_island_mod:shengji_4>, <liquid:pyrotheum>*500, 5000);
mods.thermalexpansion.Compactor.addPressRecipe(<extendedcrafting:material:2>, <extendedcrafting:material>*2, 4000);
//熔盐炉
mods.thermalexpansion.Crucible.addRecipe(<liquid:knightslime>*144, <tconstruct:ingots:3>, 4000);
mods.thermalexpansion.Crucible.addRecipe(<liquid:alubrass>*144, <tconstruct:ingots:5>, 4000);
mods.thermalexpansion.Crucible.addRecipe(<liquid:pigiron>*144, <tconstruct:ingots:4>, 4000);
mods.thermalexpansion.Crucible.addRecipe(<liquid:electrical_steel>*144, <enderio:item_alloy_ingot>, 4000);
mods.thermalexpansion.Crucible.addRecipe(<liquid:energetic_alloy>*144, <enderio:item_alloy_ingot:1>, 4000);
mods.thermalexpansion.Crucible.addRecipe(<liquid:vibrant_alloy>*144, <enderio:item_alloy_ingot:2>, 4000);
mods.thermalexpansion.Crucible.addRecipe(<liquid:redstone_alloy>*144, <enderio:item_alloy_ingot:3>, 4000);
mods.thermalexpansion.Crucible.addRecipe(<liquid:conductive_iron>*144, <enderio:item_alloy_ingot:4>, 4000);
mods.thermalexpansion.Crucible.addRecipe(<liquid:pulsating_iron>*144, <enderio:item_alloy_ingot:5>, 4000);
mods.thermalexpansion.Crucible.addRecipe(<liquid:dark_steel>*144, <enderio:item_alloy_ingot:6>, 4000);
mods.thermalexpansion.Crucible.addRecipe(<liquid:soularium>*144, <enderio:item_alloy_ingot:7>, 4000);
mods.thermalexpansion.Crucible.addRecipe(<liquid:end_steel>*144, <enderio:item_alloy_ingot:8>, 4000);
mods.thermalexpansion.Crucible.addRecipe(<liquid:construction_alloy>*144, <enderio:item_alloy_ingot:9>, 4000);
mods.thermalexpansion.Crucible.addRecipe(<liquid:crude_steel>*144, <enderio:item_alloy_endergy_ingot:0>, 4000);
mods.thermalexpansion.Crucible.addRecipe(<liquid:crystalline_alloy>*144, <enderio:item_alloy_endergy_ingot:1>, 4000);
mods.thermalexpansion.Crucible.addRecipe(<liquid:melodic_alloy>*144, <enderio:item_alloy_endergy_ingot:2>, 4000);
mods.thermalexpansion.Crucible.addRecipe(<liquid:stellar_alloy>*144, <enderio:item_alloy_endergy_ingot:3>, 4000);
mods.thermalexpansion.Crucible.addRecipe(<liquid:crystalline_pink_slime>*144, <enderio:item_alloy_endergy_ingot:4>, 4000);
mods.thermalexpansion.Crucible.addRecipe(<liquid:energetic_silver>*144, <enderio:item_alloy_endergy_ingot:5>, 4000);
mods.thermalexpansion.Crucible.addRecipe(<liquid:vivid_alloy>*144, <enderio:item_alloy_endergy_ingot:6>, 4000);
mods.thermalexpansion.Crucible.addRecipe(<liquid:uranium>*144, <immersiveengineering:metal:5>, 4000);
mods.thermalexpansion.Crucible.addRecipe(<liquid:uranium>*144, <mekanism:ingot:8>, 4000);
mods.thermalexpansion.Crucible.addRecipe(<liquid:uranium>*16, <immersiveengineering:metal:25>, 500);
mods.thermalexpansion.Crucible.addRecipe(<liquid:uranium>*16, <mekanism:nugget:8>, 500);
mods.thermalexpansion.Crucible.addRecipe(<liquid:uranium>*1296, <chisel:blockuranium:*>, 32000);
mods.thermalexpansion.Crucible.addRecipe(<liquid:uranium>*1296, <mekanism:basicblock2:10>, 32000);
mods.thermalexpansion.Crucible.addRecipe(<liquid:uranium>*1296, <ic2:resource:10>, 32000);
mods.thermalexpansion.Crucible.addRecipe(<liquid:uranium>*1296, <immersiveengineering:storage:5>, 32000);
